#define UNIFORM_SLOT    0
#define NEAREST_SAMPLER_SLOT 1
#define LINEAR_SAMPLER_SLOT 2
#define MIPMAP_SAMPLER_SLOT 3
#define BASE_TEXTURE_SLOT 4
#define EMISSIVE_TEXTURE_SLOT 5
#define NORMAL_TEXTURE_SLOT 6
#define METALLICROUGHNESS_TEXTURE_SLOT 7
#define ENVMAP_TEXTURE_SLOT 8

#define VS_INPUT_POSITION 0
#define VS_INPUT_TEXCOORD 1
#define VS_INPUT_TEXCOORD2 2
#define VS_INPUT_NORMAL 3
#define VS_INPUT_TANGENT 4

#define VS_OUTPUT_TEXCOORD 0
#define VS_OUTPUT_TEXCOORD2 1
#define VS_OUTPUT_NORMAL 2
#define VS_OUTPUT_WORLDPOS 3
#define VS_OUTPUT_TANGENT 4
